### ISSUE TITLE
server gets terminated when I use swcplugin

### ISSUE THREAD

**Issue by 5war00p** [blitz-js/next-superjson-plugin#103]
### Verify Next.js canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Describe the bug

After installing & configuring in `next.config.js` when I restart the server and try to access page, the server gets terminated without any error logs.

### Expected behavior

Expecting serialization works properly

### Version

^0.6.2

### Config

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    swcPlugins: [
      [
        "next-superjson-plugin",
        {
          excluded: [],
        },
      ],
    ],
  },
};

export default nextConfig;
```

**Comment by barrynorman** [comment]
Same for me.

**Comment by 5war00p** [comment]
Btw I'm using the Next.js App directory

**Comment by avarayr** [comment]
https://github.com/blitz-js/next-superjson-plugin/issues/102#issuecomment-1974914232

**Comment by orionmiz** [comment]
There was a breaking change in swc_ast and guessing it's the cause of this issue.

Please try again with the updated(v0.6.3) plugin applied.

**Comment by 5war00p** [comment]
https://github.com/blitz-js/next-superjson-plugin/issues/102#issuecomment-1975073713
