### ISSUE TITLE
getInitialProps is not supported

### ISSUE THREAD

**Issue by zoriya** [blitz-js/next-superjson-plugin#11]
### Describe the bug

getInitialProps is not the recommended way of passing props to components anymore, but it has not been deprecated. I think this plugin should support it.

### Expected behavior

The getInitialProps output should be converted to SuperJson.

### Version

0.3.0

### Config

```javascript
module.exports = {
	reactStrictMode: true,
	swcMinify: true,
	experimental: {
		swcPlugins: [
			[
				"next-superjson-plugin",
				{
					excluded: [],
				},
			],
		],
	},
}
```

**Comment by orionmiz** [comment]
Thanks for suggesting new feature!

This feature will be included in next release.
