### ISSUE TITLE
Error serializing with getStaticPaths

### ISSUE THREAD

**Issue by nabi-chan** [blitz-js/next-superjson-plugin#2]
Hi @orionmiz and Thanks for make king-wang-zzang (very wonderful) package :)
However, When I getStaticPaths with NextJS 12.2.4, It's throws SerializableError It came from looks like not serializing

Is that expected behavior? And Can you know how to fix it?
Thank you :)

**Comment by nabi-chan** [comment]
You can see my code at this link : https://github.com/KimPinot/new-blog/commit/41c164d2b888bd65445d4a6779cded686cc621cd

**Comment by orionmiz** [comment]
Found in `next.config.js`:
```js
swcPlugins: ["next-superjson-plugin"],
```
Correct usage of the plugin:
```js
swcPlugins: [["next-superjson-plugin", { excluded: [] }]],
```

To apply the SWC plugin, Next.js requires a tuple as an array containing both the name and the options of the plugin.
https://nextjs.org/docs/advanced-features/compiler#swc-plugins-experimental

I checked good-working of your project with the replaced configuration above,

Try it!

**Comment by nabi-chan** [comment]
It works! thank you :)

**Comment by nabi-chan** [comment]
Oh, Did you checked this commit? https://github.com/KimPinot/new-blog/commit/95634fc7f22c6d53dc64899dcae23cf8ab66577a

I forgotten mention that, This commits changes Date type to number at `/modules/post/article.ts`
When I roll-backed this commit Error shown. 🥲

Do you have a clue about this?

**Comment by nabi-chan** [comment]
You can reproduce this issue on here [KimPinot/new-blog/`nextjs-superjson`](https://github.com/KimPinot/new-blog/tree/nextjs-superjson)

**Comment by orionmiz** [comment]
Sorry, I can't guess the error you are talking about.

Please make a new issue with more detailed explanations.
