### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by cellulosa** [blitz-js/next-superjson-plugin#31]
### Describe the bug

Yo updated my `package.json` with `"next-superjson-plugin": "^0.4.2",` (and `"next": "^12.3.0",`). This is what I get:

	npm install
	npm ERR! code ERESOLVE
	npm ERR! ERESOLVE unable to resolve dependency tree
	npm ERR! 
	npm ERR! While resolving: app@1.0.0
	npm ERR! Found: next@12.3.0
	npm ERR! node_modules/next
	npm ERR!   next@"^12.3.0" from the root project
	npm ERR! 
	npm ERR! Could not resolve dependency:
	npm ERR! peer next@">12.3.0" from next-superjson-plugin@0.4.2
	npm ERR! node_modules/next-superjson-plugin
	npm ERR!   next-superjson-plugin@"^0.4.2" from the root project
	npm ERR! 
	npm ERR! Fix the upstream dependency conflict, or retry
	npm ERR! this command with --force, or --legacy-peer-deps
	npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

`--force` does not help. Am I missing something?

### Expected behavior

to install next-superjson-plugin 0.4.2 with the canary version of next (12.3.0).

### Version

0.4.2

**Comment by cellulosa** [comment]
I could install using `--legacy-peer-deps`.

**Comment by orionmiz** [comment]
You can't reach the canary with `^12.3.0`

Use `npm install next@canary` instead.

**Comment by cellulosa** [comment]
Ahhh apologies I thought `12.3.0` was the canary version 🫣
