### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nehalist** [blitz-js/next-superjson-plugin#46]
### Verify Next.js canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Describe the bug

I've installed a clean Next.js using TypeScript:

- Linux Mint 20.2
- Node 16
- Next.js 12

After installing the plugin I receive

> Segmentation fault (core dumped)

As soon as I open the app.

I'm not really sure if this is related to #34, but I got a lot of thread panics while using TypeScript path aliases. After getting rid of them the said error remains.

### Expected behavior

It shouldn't die.

### Reproduction link

https://github.com/nehalist/next-superjson-plugin-issue

### Version

0.4.8

**Comment by orionmiz** [comment]
@nehalist Please use Next.js canary version.

```bash
npm install next@canary
yarn add next@canary
pnpm add next@canary
```

That reproduction from link uses v12.3.1, not canary.

**Comment by sk-shishi** [comment]
I'm having this problem with next.js `13.2.4`. Removing `next-superjson-plugin` from `swcPlugins` and it's working again.
