### ISSUE TITLE
_app.tsx not getting parsed data

### ISSUE THREAD

**Issue by tzelon-cypator** [blitz-js/next-superjson-plugin#54]
### Verify Next.js canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Describe the bug

I'm using getServerSideProps to fetch some data and return it in props and in the `_app.tsx` file I want to use that data. 
The problem is, I have a few bigint properties in the data but in the `_app.tsx` file bigint are still strings.
I checked on the page itself and the data are parsed as expected bigint are bigint. 

### Expected behavior

parsed the data. 

### Version

0.4.9

### Config

```javascript
experimental: {
      swcPlugins: [
        [
          "next-superjson-plugin",
          {
            excluded: [],
          },
        ],
      ],
    },
```

### Additional context

   next:  v12.3.2-canary.43

**Comment by orionmiz** [comment]
Do you want to get deserialized props by reading `pageProps` of `AppProps`?

If so, use the `deserializeProps` utility function.
``` tsx
// _app.tsx
import type { AppProps } from "next/app";
import { deserializeProps } from 'next-superjson-plugin/tools'

export default function App({ Component, pageProps }: AppProps) {
  const deserialized = deserializeProps(pageProps);
  // ...
  return <Component {...pageProps} />;
}
```

**Comment by tzelon-cypator** [comment]
It seems like it stringify bigints as strings, but in the `_app.tsx` I get a simple deserialize object with the bigints still as string. 
the object I return from `getServerSideProps`
```js
{
  id: 1,
  version: 1,
  price_min: 1n,
  price_max: 999999999n,
  size_min: 1n,
  size_max: 9999999999999n,
}
```
what I receive in `_app.tsx`
```js
{
  id: 1,
  version: 1,
  price_min: "1",
  price_max: "999999999",
  size_min: "1",
  size_max: "9999999999999",
}
```

**Comment by orionmiz** [comment]
That's the expected consequences, not the bug.

See the `_superjson` property that might be included in the received value:
```ts
{
  id: 1,
  version: 1,
  price_min: "1",
  price_max: "999999999",
  size_min: "1",
  size_max: "9999999999999",
  _superjson: {values: {…}} // this property contains type data
}
```

Actual deserialization is being done by the component in the way of referring to the `_superjson` property.
So you should deserialize the `pageProps` manually to take the original props, especially within `_app.tsx`.

If you can't find `_superjson` property in the received value or the solution above wasn't helpful,
please provide a minimal reproduction, I'll take a look at it.
