### ISSUE TITLE
Children are undefined in client components rendered by RSCs

### ISSUE THREAD

**Issue by samtgarson** [blitz-js/next-superjson-plugin#63]
### Verify Next.js canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Describe the bug

It seems that `children` passed to Client components with `data-superjson` attributes are not present in the client component?

### Expected behavior

I would expect `children` to be passed through transparently to the Client component as it is without the superjson integration.

### Reproduction link

https://github.com/samtgarson/appdir-reproduction-app/tree/superjson

### Version

0.5.3

### Config

```javascript
/** @type {import("next").NextConfig} */
module.exports = {
  reactStrictMode: true,
  experimental: {
    appDir: true,
    swcPlugins: [["next-superjson-plugin", { excluded: ["children"] }]],
  },
};


(Have tried with and without the `excluded` option)
```

**Comment by orionmiz** [comment]
Thanks for reporting an issue!

The plugin v0.5.4 with bug fixes has been released.

**Comment by samtgarson** [comment]
Thanks for the quick fix 🙌
