### ISSUE TITLE
Rerendering everything if used with NextJs 13

### ISSUE THREAD

**Issue by limury** [blitz-js/next-superjson-plugin#67]
When using the experimental app dir in NextJS 13, this module causes everything to rerender every few seconds.

How to replicate:
- Install the module:
`npm install superjson next-superjson-plugin`
- Start the development server:
`npm run dev`

Additionally, the issue persists after running `npm remove superjson next-superjson-plugin` and removing the settings from `next.config.js`.

**Comment by joulev** [comment]
I can't reproduce this behaviour. Maybe it was caused by something else that you happened to add at the same time as this plugin.
