### ISSUE TITLE
Plugin broke with Next 13.4.4

### ISSUE THREAD

**Issue by EvHaus** [blitz-js/next-superjson-plugin#84]
### Verify Next.js canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Describe the bug

After upgrading from Next 13.4.3 to 13.4.4 using `next-superjson-plugin` now throws the following error during build:

```
- error ./node_modules/.pnpm/next@13.4.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/dev/amp-dev.js
Error: Filesystem cache is not enabled, cannot read plugin from phsyical path
- wait compiling...
- error ./node_modules/.pnpm/next@13.4.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/dev/amp-dev.js
Error: Filesystem cache is not enabled, cannot read plugin from phsyical path
```

Looks like that error is coming from `swc` but I'm not sure what changed between 13.4.3 and 13.4.4 that could use that.

### Expected behavior

App should still run with `next dev`

### Version

0.5.8

### Config

```javascript
// @ts-check

/**
 * @type {import('next').NextConfig}
 **/
module.exports = {
	experimental: {
		esmExternals: true,
		swcPlugins: [
			['next-superjson-plugin', {}],
		],
	},
	pageExtensions: ['page.tsx', 'page.ts'],
	reactStrictMode: true,
};
```
```


### Additional context

_No response_

**Comment by kishan-getstarted** [comment]
I got the same error yesterday. We are using nx workspace to run the nextjs application here are my configs



```
const withNx = require('@nx/next/plugins/with-nx');
const path = require('path');
/**
 * @type {import('@nx/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  pageExtensions: ['mdx', 'md', 'jsx', 'js', 'tsx', 'ts'],
  experimental: {
    swcPlugins: [["next-superjson-plugin", {}]],
  },
  sassOptions: {
    includePaths: [path.join(__dirname, 'styles')],
  },
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
};

module.exports = withNx(nextConfig);

```

**Comment by Lagyu** [comment]
I am experiencing the same error, by running `yaarn build`.
Removing swcPlugins from nextConfig or reverting next version to 13.4.3 fixed the problem for me.

**Comment by tarunfy** [comment]
Hey, I got this same issue.
Using: Nextjs 13.4.4

<img width="1061" alt="Screenshot 2023-06-02 at 3 07 57 PM" src="https://github.com/blitz-js/next-superjson-plugin/assets/51208270/7c038624-d478-4551-ae7e-1e9086c307bf">

**Comment by aaronlin0122** [comment]
Same here

![image](https://github.com/blitz-js/next-superjson-plugin/assets/47508893/11cbead2-aa2b-45c6-b075-0b8bd209d768)

**Comment by orionmiz** [comment]
https://github.com/vercel/next.js/pull/50651

This PR will close the issue.

**Comment by orionmiz** [comment]
Please check out [v13.4.5-canary.7](https://github.com/vercel/next.js/releases/tag/v13.4.5-canary.7)
